### ISSUE TITLE
[ERROR]server console

### ISSUE THREAD

**Issue by lodest-game** [tom5454/Create-Ore-Excavation#33]
[16:27:48] [Worker-Main-27/error] [minecraft/SimpleJsonResourceReloadListener]: Couldn't parse data file createoreexcavation:crushing/redstone_crushing from createoreexcavation:recipes/crushing/redstone_crushing.json
com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:505) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:542) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:52) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:A}
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:20) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:A}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,re:computing_frames,re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
Caused by: java.io.EOFException: End of input at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:661) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866) ~[gson-2.8.9.jar%2321!/:?] {}
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:503) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:classloading,re:mixin}
	... 11 more
[16:27:48] [Worker-Main-27/error] [minecraft/SimpleJsonResourceReloadListener]: Couldn't parse data file createoreexcavation:cutting/diamond_cutting from createoreexcavation:recipes/cutting/diamond_cutting.json
com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:505) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:542) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:52) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:A}
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:20) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:A}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,re:computing_frames,re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
Caused by: java.io.EOFException: End of input at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:661) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866) ~[gson-2.8.9.jar%2321!/:?] {}
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:503) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:classloading,re:mixin}
	... 11 more
[16:27:48] [Worker-Main-27/error] [minecraft/SimpleJsonResourceReloadListener]: Couldn't parse data file createoreexcavation:cutting/emerald_cutting from createoreexcavation:recipes/cutting/emerald_cutting.json
com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:505) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:542) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:52) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:A}
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:20) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:A}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,re:computing_frames,re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
Caused by: java.io.EOFException: End of input at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:661) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866) ~[gson-2.8.9.jar%2321!/:?] {}
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:503) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:classloading,re:mixin}
	... 11 more
[16:27:48] [Worker-Main-27/error] [minecraft/SimpleJsonResourceReloadListener]: Couldn't parse data file createoreexcavation:drilling/hardened_diamond from createoreexcavation:recipes/drilling/hardened_diamond.json
com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:505) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:542) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:52) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:A}
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:20) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:A}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,re:computing_frames,re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
Caused by: java.io.EOFException: End of input at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:661) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866) ~[gson-2.8.9.jar%2321!/:?] {}
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:503) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:classloading,re:mixin}
	... 11 more
[16:27:48] [Worker-Main-27/error] [minecraft/SimpleJsonResourceReloadListener]: Couldn't parse data file createoreexcavation:milling/redstone_milling from createoreexcavation:recipes/milling/redstone_milling.json
com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:505) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:542) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:52) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:A}
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:20) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:A}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,re:computing_frames,re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
Caused by: java.io.EOFException: End of input at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1395) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:661) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar%2321!/:?] {}
	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866) ~[gson-2.8.9.jar%2321!/:?] {}
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:503) ~[server-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:classloading,re:mixin}
	... 11 more

**Comment by tom5454** [comment]
Please post your minecraft log

**Comment by lodest-game** [comment]
[debug.log](https://github.com/tom5454/Create-Ore-Excavation/files/11616152/debug.log)
[latest.log](https://github.com/tom5454/Create-Ore-Excavation/files/11616154/latest.log)
Thanks for your work and Good luck

**Comment by lodest-game** [comment]
no,I think I sent the wrong report，let me check it.Sorry

**Comment by lodest-game** [comment]
[debug.log](https://github.com/tom5454/Create-Ore-Excavation/files/11616379/debug.log)
[latest.log](https://github.com/tom5454/Create-Ore-Excavation/files/11616384/latest.log)
this is new log.

**Comment by tom5454** [comment]
It's Create Ore Excavation Plus.
mikeee1/create_ore_excavation_plus#5

**Comment by lodest-game** [comment]
thanks
