### ISSUE TITLE
1.20.1 version random crashing when put to use.

### ISSUE THREAD

**Issue by WilliamBlaze** [tom5454/Create-Ore-Excavation#49]
The entirety of the crash log are in the pastebin link below, the list of mods used at the time is included at the bottom of the crash log.

https://pastebin.com/qvnzBadB

**Comment by tom5454** [comment]
The game never reaches any of my code, it crashes inside minecraft's block entity handler for some reason. It could be an incompatibility caused by another mod.

**Comment by WilliamBlaze** [comment]
then I'm entirely confused by this part of the log right at the top


---- Minecraft Crash Report ----
// I let you down. Sorry :(
 
Time: 2023-08-16 14:35:18
Description: Ticking block entity
 
java.lang.NullPointerException: Ticking block entity
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:699) ~[client-1.20.1-20230612.114412-srg.jar%23528!/:?] {re:classloading,pl:accesstransformer:B}
-- Block entity being ticked --
Details:
	Name: **createoreexcavation:drill** // com.tom.createores.block.entity.DrillBlockEntity
	Block: **Block{createoreexcavation:drilling_machine}**[facing=north]
	Block location: World: (-110,-22,-392), Section: (at 2,10,8 in -7,-2,-25; chunk contains blocks -112,-64,-400 to -97,319,-385), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Block: Block{createoreexcavation:drilling_machine}[facing=north]
	Block location: World: (-110,-22,-392), Section: (at 2,10,8 in -7,-2,-25; chunk contains blocks -112,-64,-400 to -97,319,-385), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Block Entity NBT: {drill:{Count:0b,id:"minecraft:air"},inv:[],progress:0,tank:{Amount:0,FluidName:"minecraft:empty"}}
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:699) ~[client-1.20.1-20230612.114412-srg.jar%23528!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[client-1.20.1-20230612.114412-srg.jar%23528!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[client-1.20.1-20230612.114412-srg.jar%23528!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:multiverse.mixins.json:LevelMixin,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[client-1.20.1-20230612.114412-srg.jar%23528!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:multiverse.mixins.json:ServerLevelMixin,pl:mixin:APP:sleep_tight-common.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:modulargolems.mixins.json:ServerLevelMixin,pl:mixin:APP:thinair.common.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23528!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23528!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23528!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23528!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23528!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

**Comment by tom5454** [comment]
The game is trying to tick the drilling machine but it crashes inside the vanilla tick handler.
`net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:699)`
Also 699 is not a valid line number. I have no idea what is crashing, as it never reaches my code.
Try removing any optimization mods that may mess with this.
