### ISSUE TITLE
Chunk Crash / Possible incompatibility

### ISSUE THREAD

**Issue by Quadrum1** [tom5454/Create-Ore-Excavation#72]
This mod appears to be generating very rare and infrequent crashes when running on a server.
The log can be found below.

Is there any way to fix this? I would like to continue playing with this mod, as the premise appeared quite fun, but do not want to keep encountering these crashes.

Funnily enough, of the 4 crashes we had in the last ~24 hours, only two generated any log at all, both with the same structure.

[19:09:50] [C2ME worker #1/ERROR]: Failed to save chunk -178,-125 asynchronously, falling back to sync saving
java.util.concurrent.CompletionException: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at net.minecraft.class_2852.handler$bii000$chunk-storage-api-fabric$onWrite(class_2852.java:1122) ~[server-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:354) ~[server-intermediary.jar:?]
	at com.ishland.c2me.base.common.registry.SerializerAccess.lambda$static$0(SerializerAccess.java:14) ~[c2me-base-0.2.0+alpha.11.0-fa6449962c00bc10.jar:?]
	at net.minecraft.class_3898.mddb1d7c$c2me-threading-chunkio$lambda$asyncSave$17$e(class_3898.java:11262) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
[19:11:22] [C2ME worker #1/ERROR]: Failed to save chunk -205,-103 asynchronously, falling back to sync saving
java.util.concurrent.CompletionException: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at net.minecraft.class_2852.handler$bii000$chunk-storage-api-fabric$onWrite(class_2852.java:1122) ~[server-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:354) ~[server-intermediary.jar:?]
	at com.ishland.c2me.base.common.registry.SerializerAccess.lambda$static$0(SerializerAccess.java:14) ~[c2me-base-0.2.0+alpha.11.0-fa6449962c00bc10.jar:?]
	at net.minecraft.class_3898.mddb1d7c$c2me-threading-chunkio$lambda$asyncSave$17$e(class_3898.java:11262) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
[19:11:22] [C2ME worker #1/ERROR]: Failed to save chunk -203,-103 asynchronously, falling back to sync saving
java.util.concurrent.CompletionException: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at net.minecraft.class_2852.handler$bii000$chunk-storage-api-fabric$onWrite(class_2852.java:1122) ~[server-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:354) ~[server-intermediary.jar:?]
	at com.ishland.c2me.base.common.registry.SerializerAccess.lambda$static$0(SerializerAccess.java:14) ~[c2me-base-0.2.0+alpha.11.0-fa6449962c00bc10.jar:?]
	at net.minecraft.class_3898.mddb1d7c$c2me-threading-chunkio$lambda$asyncSave$17$e(class_3898.java:11262) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
[19:11:22] [C2ME worker #1/ERROR]: Failed to save chunk -204,-103 asynchronously, falling back to sync saving
java.util.concurrent.CompletionException: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at net.minecraft.class_2852.handler$bii000$chunk-storage-api-fabric$onWrite(class_2852.java:1122) ~[server-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:354) ~[server-intermediary.jar:?]
	at com.ishland.c2me.base.common.registry.SerializerAccess.lambda$static$0(SerializerAccess.java:14) ~[c2me-base-0.2.0+alpha.11.0-fa6449962c00bc10.jar:?]
	at net.minecraft.class_3898.mddb1d7c$c2me-threading-chunkio$lambda$asyncSave$17$e(class_3898.java:11262) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
[19:11:22] [C2ME worker #1/ERROR]: Failed to save chunk -202,-103 asynchronously, falling back to sync saving
java.util.concurrent.CompletionException: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at net.minecraft.class_2852.handler$bii000$chunk-storage-api-fabric$onWrite(class_2852.java:1122) ~[server-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:354) ~[server-intermediary.jar:?]
	at com.ishland.c2me.base.common.registry.SerializerAccess.lambda$static$0(SerializerAccess.java:14) ~[c2me-base-0.2.0+alpha.11.0-fa6449962c00bc10.jar:?]
	at net.minecraft.class_3898.mddb1d7c$c2me-threading-chunkio$lambda$asyncSave$17$e(class_3898.java:11262) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
[19:11:22] [C2ME worker #1/ERROR]: Failed to save chunk -215,-103 asynchronously, falling back to sync saving
java.util.concurrent.CompletionException: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at net.minecraft.class_2852.handler$bii000$chunk-storage-api-fabric$onWrite(class_2852.java:1122) ~[server-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:354) ~[server-intermediary.jar:?]
	at com.ishland.c2me.base.common.registry.SerializerAccess.lambda$static$0(SerializerAccess.java:14) ~[c2me-base-0.2.0+alpha.11.0-fa6449962c00bc10.jar:?]
	at net.minecraft.class_3898.mddb1d7c$c2me-threading-chunkio$lambda$asyncSave$17$e(class_3898.java:11262) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
[19:11:22] [C2ME worker #1/ERROR]: Failed to save chunk -216,-103 asynchronously, falling back to sync saving
java.util.concurrent.CompletionException: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at net.minecraft.class_2852.handler$bii000$chunk-storage-api-fabric$onWrite(class_2852.java:1122) ~[server-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:354) ~[server-intermediary.jar:?]
	at com.ishland.c2me.base.common.registry.SerializerAccess.lambda$static$0(SerializerAccess.java:14) ~[c2me-base-0.2.0+alpha.11.0-fa6449962c00bc10.jar:?]
	at net.minecraft.class_3898.mddb1d7c$c2me-threading-chunkio$lambda$asyncSave$17$e(class_3898.java:11262) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
[19:11:22] [C2ME worker #1/ERROR]: Failed to save chunk -213,-103 asynchronously, falling back to sync saving
java.util.concurrent.CompletionException: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at net.minecraft.class_2852.handler$bii000$chunk-storage-api-fabric$onWrite(class_2852.java:1122) ~[server-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:354) ~[server-intermediary.jar:?]
	at com.ishland.c2me.base.common.registry.SerializerAccess.lambda$static$0(SerializerAccess.java:14) ~[c2me-base-0.2.0+alpha.11.0-fa6449962c00bc10.jar:?]
	at net.minecraft.class_3898.mddb1d7c$c2me-threading-chunkio$lambda$asyncSave$17$e(class_3898.java:11262) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
[19:11:22] [C2ME worker #1/ERROR]: Failed to save chunk -214,-103 asynchronously, falling back to sync saving
java.util.concurrent.CompletionException: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at net.minecraft.class_2852.handler$bii000$chunk-storage-api-fabric$onWrite(class_2852.java:1122) ~[server-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:354) ~[server-intermediary.jar:?]
	at com.ishland.c2me.base.common.registry.SerializerAccess.lambda$static$0(SerializerAccess.java:14) ~[c2me-base-0.2.0+alpha.11.0-fa6449962c00bc10.jar:?]
	at net.minecraft.class_3898.mddb1d7c$c2me-threading-chunkio$lambda$asyncSave$17$e(class_3898.java:11262) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
[19:11:22] [C2ME worker #1/ERROR]: Failed to save chunk -211,-103 asynchronously, falling back to sync saving
java.util.concurrent.CompletionException: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_2839 cannot be cast to class com.tom.chunkstorage.impl.LevelChunkAccess (net.minecraft.class_2839 and com.tom.chunkstorage.impl.LevelChunkAccess are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @573f2bb1)
	at net.minecraft.class_2852.handler$bii000$chunk-storage-api-fabric$onWrite(class_2852.java:1122) ~[server-intermediary.jar:?]
	at net.minecraft.class_2852.method_12410(class_2852.java:354) ~[server-intermediary.jar:?]
	at com.ishland.c2me.base.common.registry.SerializerAccess.lambda$static$0(SerializerAccess.java:14) ~[c2me-base-0.2.0+alpha.11.0-fa6449962c00bc10.jar:?]
	at net.minecraft.class_3898.mddb1d7c$c2me-threading-chunkio$lambda$asyncSave$17$e(class_3898.java:11262) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
[19:11:22] [C2ME worker #1/ERROR]: Failed to save chunk -210,-103 asynchronously, falling back to sync saving
java.util.concurrent.CompletionException: java.lang.ClassCastException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassCastException
[19:11:22] [C2ME worker #1/ERROR]: Failed to save chunk -217,-103 asynchronously, falling back to sync saving
java.util.concurrent.CompletionException: java.lang.ClassCastException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassCastException
[19:11:22] [C2ME worker #1/ERROR]: Failed to save chunk -218,-103 asynchronously, falling back to sync saving
java.util.concurrent.CompletionException: java.lang.ClassCastException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassCastException
[19:12:14] [Worker-Main-2/WARN]: Empty or non-existent pool: kaisyn:village/exclusives/mediterranean/villager_bishop
[19:12:28] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-423, y=-50, z=-211}
[19:12:28] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-420, y=-50, z=-211}
[19:12:28] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-195, y=-54, z=-92}
[19:12:28] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-192, y=-54, z=-88}
[19:12:28] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-192, y=-50, z=-85}
[19:12:28] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-183, y=-51, z=-89}
[19:12:28] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-186, y=-50, z=-90}
[19:12:28] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-186, y=-45, z=-87}
[19:12:28] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-189, y=-45, z=-84}
[19:12:28] [Worker-Main-2/ERROR]: No key selector in MapLike[{event_delay:0,event_distance:0.0f,range:8,source:{pos:[I;-425,-56,-205],type:"minecraft:block"}}]
[19:12:28] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-192, y=-54, z=-74}
[19:12:28] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-192, y=-50, z=-77}
[19:12:28] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-187, y=-50, z=-72}
[19:12:28] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-184, y=-45, z=-75}
[19:12:28] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-182, y=-45, z=-75}
[19:12:31] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-418, y=-50, z=-208}
[19:12:31] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-177, y=-55, z=-77}
[19:12:31] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-181, y=-50, z=-73}
[19:12:31] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-172, y=-54, z=-70}
[19:12:31] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-276, y=-57, z=-243}
[19:12:32] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-413, y=-49, z=-217}
[19:12:32] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-178, y=-45, z=-85}
[19:12:32] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-178, y=-41, z=-89}
[19:12:32] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-172, y=-54, z=-92}
[19:12:32] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-172, y=-54, z=-93}
[19:12:32] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-175, y=-41, z=-90}
[19:12:32] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-274, y=-57, z=-245}
[19:12:32] [Worker-Main-2/ERROR]: Hanging entity at invalid position: class_2338{x=-277, y=-57, z=-244}

**Comment by Quadrum1** [comment]
I'm pretty sure it's more the fault of [C2ME](https://modrinth.com/mod/c2me-fabric), but I wanted to post the issue here as well :)
